### ISSUE TITLE
Quick tutorial that I wrote up about importing source engine maps into RRS.

### ISSUE THREAD

**Issue by techsideofficial** [Alexa-RR/StudioDocs#84]
Modify this as you wish: [https://xan.fandom.com/wiki/BSP_To_Unity](url)

**Comment by Alexa-RR** [comment]
hiiiiiiii, (totally did not see this for an entire month), my vision for the studio docs is all about how to help someone to create amazing things in studio :D, I don't think a section on how to import objects or entire maps into studio would fit, 

thanks for the suggestion tho <3
